animate/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('reviews.urls')),
    path('admin/', admin.site.urls),
]

reviews/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("anime/<int:anime_id>", views.anime, name="anime"),
    path("random/", views.random, name="random"),
    path("like/<int:review_id>", views.like, name="like"),
    path("dislike/<int:review_id>", views.dislike, name="dislike"),
    path("profile/<str:username>", views.profile, name="profile"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register")
]

reviews/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    id = models.BigAutoField(primary_key=True)
    pass


class Review(models.Model):
    RECOMMENDATION = [
        ('RE', 'Recommended'),
        ('MF', 'Mixed Feelings'),
        ('NR', 'Not Recommended')
    ]

    id = models.BigAutoField(primary_key=True)
    anime_id = models.IntegerField()
    anime_title = models.CharField(max_length=256)
    content = models.TextField()
    recommendation = models.CharField(max_length=2, choices=RECOMMENDATION, default=None)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reviews')
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Review on anime {self.anime_id}: {self.anime_title} by {self.author}'
    

class Like(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes')
    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='likes')


class Dislike(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='dislikes')
    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='dislikes')

reviews/forms.py
from django import forms

from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['content', 'recommendation']
        widgets = {
            'content': forms.Textarea(attrs={'rows': '5'}),
            'recommendation': forms.RadioSelect()
        }
        labels = {
            'content': '',
            'recommendation': 'Would you recommend this anime?'
        }

reviews/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.db.models import Count
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import requests
import json

from .models import User, Review, Like, Dislike
from .forms import ReviewForm


def index(request):
    query = request.GET.get('q')
    if query:
        return render(request, 'reviews/search.html', {
            'query': query
        })

    return render(request, 'reviews/index.html')


def random(request):
    response = requests.get('https://api.jikan.moe/v4/random/anime')
    data = json.loads(response.text)
    anime = data['data']

    messages.success(request, 'Random anime chosen!')
    return HttpResponseRedirect(reverse('anime', kwargs={'anime_id': anime['mal_id']}))


def anime(request, anime_id):
    response = requests.get(f'https://api.jikan.moe/v4/anime/{anime_id}')
    data = json.loads(response.text)
    anime = data['data']

    sorting = request.GET.get('sort-by')
    selected = {
        'latest': False,
        'oldest': False,
        'likes': False,
        'dislikes': False
    }

    if sorting == 'oldest':
        reviews = Review.objects.filter(anime_id=anime_id).order_by('time')
        selected['oldest'] = True
    elif sorting == 'likes':
        reviews = (
            Review.objects.filter(anime_id=anime_id)
            .annotate(like_count=Count('likes'))
            .order_by('-like_count')
        )
        selected['likes'] = True
    elif sorting == 'dislikes':
        reviews = (
            Review.objects.filter(anime_id=anime_id)
            .annotate(dislike_count=Count('dislikes'))
            .order_by('-dislike_count')
        )
        selected['dislikes'] = True
    else:
        reviews = Review.objects.filter(anime_id=anime_id).order_by('-time')
        selected['latest'] = True

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            anime_id = request.POST.get('anime_id')
            anime_title = request.POST.get('anime_title')
            content = form.cleaned_data['content']
            recommendation = form.cleaned_data['recommendation']
            author = request.user

            new_review = Review(
                anime_id=int(anime_id), anime_title=anime_title,
                content=content, recommendation=recommendation, author=author
            )
            new_review.save()

            messages.success(request, 'Review posted!')
            return HttpResponseRedirect(reverse('anime', kwargs={'anime_id': anime_id}))

    if not request.user.is_anonymous:
        user = User.objects.get(id=request.user.id)
        liked_reviews = list(map(lambda x: x.review, user.likes.all()))
        disliked_reviews = list(map(lambda x: x.review, user.dislikes.all()))

        return render(request, 'reviews/anime.html', {
            'anime': anime,
            'reviews': reviews,
            'liked_reviews': liked_reviews,
            'disliked_reviews': disliked_reviews,
            'form': ReviewForm(),
            'selected': selected
        })

    return render(request, 'reviews/anime.html', {
        'anime': anime,
        'reviews': reviews,
        'selected': selected
    })


@login_required
def like(request, review_id):
    if request.method != 'POST':
        messages.error(request, 'That method is not allowed.')
        return HttpResponseRedirect(reverse('index'))
    
    user = User.objects.get(id=request.user.id)
    review = Review.objects.get(id=review_id)

    like, created = Like.objects.get_or_create(user=user, review=review)
    dislike = Dislike.objects.filter(user=user, review=review)
    dislike_exists = dislike.exists()
    if not created:
        like.delete()
    else:
        review.likes.add(like)
        if dislike_exists:
            dislike.delete()

    return JsonResponse({'created': created, 'dislike_exists': dislike_exists}, status=201)


@login_required
def dislike(request, review_id):
    if request.method != 'POST':
        messages.error(request, 'That method is not allowed.')
        return HttpResponseRedirect(reverse('index'))
    
    user = User.objects.get(id=request.user.id)
    review = Review.objects.get(id=review_id)

    dislike, created = Dislike.objects.get_or_create(user=user, review=review)
    like = Like.objects.filter(user=user, review=review)
    like_exists = like.exists()
    if not created:
        dislike.delete()
    else:
        review.dislikes.add(dislike)
        if like_exists:
            like.delete()

    return JsonResponse({'created': created, 'like_exists': like_exists}, status=201)


def profile(request, username):
    profile_user = User.objects.get(username=username)

    sorting = request.GET.get('sort-by')
    selected = {
        'latest': False,
        'oldest': False,
        'likes': False,
        'dislikes': False
    }

    if sorting == 'oldest':
        reviews = Review.objects.filter(author=profile_user.id).order_by('time')
        selected['oldest'] = True
    elif sorting == 'likes':
        reviews = (
            Review.objects.filter(author=profile_user.id)
            .annotate(like_count=Count('likes'))
            .order_by('-like_count')
        )
        selected['likes'] = True
    elif sorting == 'dislikes':
        reviews = (
            Review.objects.filter(author=profile_user.id)
            .annotate(dislike_count=Count('dislikes'))
            .order_by('-dislike_count')
        )
        selected['dislikes'] = True
    else:
        reviews = Review.objects.filter(author=profile_user.id).order_by('-time')
        selected['latest'] = True

    if not request.user.is_anonymous:
        user = User.objects.get(id=request.user.id)
        liked_reviews = list(map(lambda x: x.review, user.likes.all()))
        disliked_reviews = list(map(lambda x: x.review, user.dislikes.all()))

        return render(request, 'reviews/profile.html', {
            'profile_username': profile_user.username,
            'reviews': reviews,
            'liked_reviews': liked_reviews,
            'disliked_reviews': disliked_reviews,
            'selected': selected
        })

    return render(request, 'reviews/profile.html', {
        'profile_username': profile_user.username,
        'reviews': reviews,
        'selected': selected
    })


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, 'Logged In!')
            return HttpResponseRedirect(reverse('index'))
        else:
            messages.error(request, 'Invalid username and/or password.')
            return render(request, 'reviews/login.html')
    else:
        return render(request, 'reviews/login.html')


def logout_view(request):
    logout(request)
    messages.success(request, 'Logged out!')
    return HttpResponseRedirect(reverse('index'))


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        email =  request.POST['email']

        password = request.POST['password']
        confirm = request.POST['confirm']
        if password != confirm:
            messages.error(request, 'Passwords must match.')
            return render(request, 'reviews/register.html')
    
        try:
            user = User.objects.create_user(username, email, password)
        except IntegrityError:
            messages.error(request, 'Username already taken.')
            return render(request, 'reviews/register.html')
        login(request, user)
        messages.success(request, 'Account created!')
        return HttpResponseRedirect(reverse('index'))

    return render(request, 'reviews/register.html')

reviews/templates/reviews/anime.html
{% extends "reviews/layout.html" %}
{% load static %}

{% block title %}
  <title>{{ anime.title }}</title>
{% endblock %}

{% block script %}
  <script src="{% static 'reviews/review.js' %}" defer></script>
  <script src="{% static 'reviews/like.js' %}" defer></script>
{% endblock %}

{% block main %}
  <section>
    <div class="section-container">
      <div class="section-wrapper">
        <form class="search-form" action="/" method="get">
          <input class="search-input" type="text" name="q" id="search" placeholder="Search anime" required>
          <button class="search-button" type="submit"><i class="fa fa-search"></i></button>
        </form>
      </div>
    </div>
  </section>
  <section>
    <div class="section-container">
      <div class="section-wrapper">
        <div class="anime-info">
          <h1>{{ anime.title }}</h1>
          {% if anime.title_synonyms %}
            <p>Also known as {% for synonym in anime.title_synonyms %} <strong>{{ synonym }}</strong>{% if not forloop.last %}, {% endif %}{% endfor %}</p>
          {% endif %}
          <div class="anime-wrapper">
            <div>
              <img src="{{ anime.images.jpg.large_image_url }}" alt="{{ anime.title }}">
            </div>
            <div>
              {% if anime.synopsis == None %}
                <p>No synopsis written yet for this anime...</p>
              {% else %}
                <p>{{ anime.synopsis }}</p>
              {% endif %}
              <h2>Information</h2>
              <p>Type: {{ anime.type }}</p>
              <p>Episodes: {%if anime.episodes %} {{anime.episodes }} {% else %} Unknown {% endif %}</p>
              <p>Status: {{ anime.status }}</p>
              <p>Aired: {{ anime.aired.string }}</p>
              <p>Genres: {% for genre in anime.genres %} {{ genre.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
              <p>Studios: 
                {% if anime.studios %}
                  {% for studio in anime.studios %} {{ studio.name }}{% if not forloop.last %}, {% endif %}{% endfor %}
                {% else %}
                  None found
                {% endif %}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section>
    <div class="section-container">
      <div class="section-wrapper">
        <div class="review-section">
          {% if user.is_authenticated %}
            <button id="review-toggle" class="button">Write a Review</button>
            <div class="review-form">
              <h2>Write a Review</h2>
              <form action="{% url 'anime' anime.mal_id %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="anime_id" value="{{ anime.mal_id }}">
                <input type="hidden" name="anime_title" value="{{ anime.title }}">
                {{ form }}
                <div class="button-wrapper">
                  <input id="cancel" class="button" type="button" value="Cancel">
                  <input class="button" type="submit" value="Post">
                </div>
              </form>
            </div>
          {% endif %}
          <div id="reviews" class="reviews">
            <h2>Reviews</h2>
            {% if reviews %}
              <div class="sorting">
                <form action="#reviews" method="get">
                  <label for="sort-by">Sort by:</label>
                  <select name="sort-by" id="sort-by">
                    <option value="latest" {% if selected.latest %} selected {% endif %}>Latest (default)</option>
                    <option value="oldest" {% if selected.oldest %} selected {% endif %}>Oldest</option>
                    <option value="likes" {% if selected.likes %} selected {% endif %}>Likes</option>
                    <option value="dislikes" {% if selected.dislikes %} selected {% endif %}>Dislikes</option>
                  </select>
                </form>
              </div>
              {% for review in reviews %}
                <div id="{{ review.id }}" class="review">
                  <div class="review-header">
                    <strong><a href="{% url 'profile' review.author %}">{{ review.author }}</a></strong>
                    <span>{{ review.time }}</span>
                  </div>
                  {% if review.recommendation == 'RE' %}
                    <div class="recommendation">
                      <i class="fa fa-star"></i>
                      {{ review.get_recommendation_display }}
                    </div>
                  {% elif review.recommendation == 'MF' %}
                    <div class="recommendation">
                      <i class="fa fa-star-half-stroke"></i>
                      {{ review.get_recommendation_display }}
                    </div>
                  {% else %}
                    <div class="recommendation">
                      <i class="fa-regular fa-star"></i>
                      {{ review.get_recommendation_display }}
                    </div>
                  {% endif %}
                  <p>{{ review.content|linebreaksbr }}</p>
                  {% if user.is_authenticated %}
                    {% if review in liked_reviews %}
                      <div class="review-interaction">
                        <div class="like highlighted" onclick="likeReview(this)">
                          <i class="fa fa-thumbs-up"></i>
                          <span>{{ review.likes.all|length }}</span>
                        </div>
                        <div class="dislike" onclick="dislikeReview(this)">
                          <i class="fa fa-thumbs-down"></i>
                          <span>{{ review.dislikes.all|length }}</span>
                        </div>
                      </div>
                    {% elif review in disliked_reviews %}
                      <div class="review-interaction">
                        <div class="like" onclick="likeReview(this)">
                          <i class="fa fa-thumbs-up"></i>
                          <span>{{ review.likes.all|length }}</span>
                        </div>
                        <div class="dislike highlighted" onclick="dislikeReview(this)">
                          <i class="fa fa-thumbs-down"></i>
                          <span>{{ review.dislikes.all|length }}</span>
                        </div>
                      </div>
                    {% else %}
                      <div class="review-interaction">
                        <div class="like" onclick="likeReview(this)">
                          <i class="fa fa-thumbs-up"></i>
                          <span>{{ review.likes.all|length }}</span>
                        </div>
                        <div class="dislike" onclick="dislikeReview(this)">
                          <i class="fa fa-thumbs-down"></i>
                          <span>{{ review.dislikes.all|length }}</span>
                        </div>
                      </div>
                    {% endif %}
                  {% endif %}
                </div>
              {% endfor %}
            {% else %}
              <p>No reviews yet! Be the first to write one!</p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

reviews/templates/reviews/index.html
{% extends "reviews/layout.html" %}
{% load static %}

{% block title %}
  <title>Animate</title>
{% endblock %}

{% block script %}
  <script src="{% static 'reviews/index.js' %}" defer></script>
{% endblock %}

{% block main %}
  <section>
    <div class="section-container">
      <div class="section-wrapper">
        <div class="cta">
          {% if user.is_authenticated %}
            <h1>Welcome to Animate, {{ user.username }}!</h1>
            <p class="cta-text">
              You have written {{ user.reviews.all|length }} {% if user.reviews.all|length == 1 %} review {% else %} reviews {% endif %} so far.
              Interested in checking out more anime? Search for a particular one in the search bar or check out the top airing ones below.
            </p>
            <div class="button-wrapper">
              <a class="button" href="{% url 'logout' %}">Log Out</a>
            </div>
          {% else %}
            <h1>Welcome to Animate!</h1>
            <p class="cta-text">
              Are you an anime fan looking for a centralized database to browse through? Look no further than Animate!
              We provide a user-friendly platform for all of your anime needs. Join the community today!
            </p>
            <div class="button-wrapper">
              <a class="button" href="{% url 'login' %}">Log In</a>
              <a class="button" href="{% url 'register' %}">Sign Up</a>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
  <section>
    <div class="section-container">
      <div class="section-wrapper">
        <div class="search-wrapper">
          <form class="search-form" action="/" method="get">
            <input class="search-input" type="text" name="q" id="search" placeholder="Search anime" required>
            <button class="search-button" type="submit"><i class="fa fa-search"></i></button>
          </form>
          <div class="button-wrapper">
            <a class="button" href="{% url 'random' %}">Random Anime</a>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section>
    <div class="section-container">
      <div class="section-wrapper">
        <div id="top-anime">
          <h2>Top Airing Anime</h2>
          <div id="top-anime-cards" class="cards"></div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

reviews/templates/reviews/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block title %}
  {% endblock %}
  <link rel="shortcut icon" href="{% static 'reviews/favicon.ico' %}" type="image/x-icon">
  <link href="{% static 'reviews/styles.css' %}" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  <script src="{% static 'reviews/dropdown.js' %}" defer></script>
  {% block script %}
  {% endblock %}
</head>
<body>
  <header>
    <div class="header-items">
      <a href="/" class="logo">
        <div class="logo-text">
          <span style="color: #fff; float: left;">ANI</span>
          <span style="color: #764d69;">MATE</span>
        </div>
      </a>
      {% if user.is_authenticated %}
        <div class="dropdown-container">
          <button class="dropdown-button dropdown" onclick="showContent(this)">
            <i class="fa fa-user dropdown"></i>
            <i class="fa fa-caret-down dropdown"></i>
          </button>
          <div class="dropdown-content">
            <p class="dropdown-username">{{ user.username }}</p>
            <a href="{% url 'profile' user.username %}">
              <i class="fa fa-user"></i>
              Profile
            </a>
            <a href="/">
              <i class="fa fa-home"></i>
              Home
            </a>
            <a href="{% url 'logout' %}">
              <i class="fa fa-sign-out"></i>
              Log Out
            </a>
          </div>
        </div>
      {% else %}
        <a href="{% url 'login' %}" class="header-auth">Log In</a>
      {% endif %}
    </div>
  </header>
  <main>
    {% if messages %}
      {% for message in messages %}
        <div class="alert {{ message.tags }}">{{ message }}</div>
      {% endfor %}
    {% endif %}
    {% block main %}
    {% endblock %}
  </main>
</body>
</html>

reviews/templates/reviews/login.html
{% extends "reviews/layout.html" %}

{% block title %}
  <title>Log In</title>
{% endblock %}

{% block main %}
  <section>
    <div class="section-container">
      <div class="section-wrapper">
        <div class="auth-wrapper">
          <h1>Log In</h1>
          <form action="{% url 'login' %}" method="post">
            {% csrf_token %}
            <div class="form-inputs">
              <label for="username">Username</label>
              <input type="text" name="username" id="username" required>
              <label for="password">Password</label>
              <input type="password" name="password" id="password" required>
              <a class="auth-link" href="{% url 'register' %}">Create an account</a>
              <div class="button-wrapper">
                <input class="button" type="submit" value="Log In">
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

reviews/templates/reviews/profile.html
{% extends "reviews/layout.html" %}
{% load static %}

{% block title %}
  <title>{{ profile_username }}'s Profile</title>
{% endblock %}

{% block script %}
  <script src="{% static 'reviews/review.js' %}" defer></script>
  <script src="{% static 'reviews/like.js' %}" defer></script>
{% endblock %}

{% block main %}
  <section>
    <div class="section-container">
      <div class="section-wrapper">
        <h1>{{ profile_username }}</h1>
      </div>
    </div>
  </section>
  <section>
    <div class="section-container">
      <div class="section-wrapper">
        <div id="reviews" class="reviews">
          <h2>Their Reviews</h2>
            {% if reviews %}
              <div class="sorting">
                <form action="#reviews" method="get">
                  <label for="sort-by">Sort by:</label>
                  <select name="sort-by" id="sort-by">
                    <option value="latest" {% if selected.latest %} selected {% endif %}>Latest (default)</option>
                    <option value="oldest" {% if selected.oldest %} selected {% endif %}>Oldest</option>
                    <option value="likes" {% if selected.likes %} selected {% endif %}>Likes</option>
                    <option value="dislikes" {% if selected.dislikes %} selected {% endif %}>Dislikes</option>
                  </select>
                </form>
              </div>
              {% for review in reviews %}
                <div id="{{ review.id }}" class="review">
                  <div class="review-header">
                    <strong><a href="{% url 'anime' review.anime_id %}">{{ review.anime_title }}</a></strong>
                    <span>{{ review.time }}</span>
                  </div>
                  {% if review.recommendation == 'RE' %}
                    <div class="recommendation">
                      <i class="fa fa-star"></i>
                      {{ review.get_recommendation_display }}
                    </div>
                  {% elif review.recommendation == 'MF' %}
                    <div class="recommendation">
                      <i class="fa fa-star-half-stroke"></i>
                      {{ review.get_recommendation_display }}
                    </div>
                  {% else %}
                    <div class="recommendation">
                      <i class="fa-regular fa-star"></i>
                      {{ review.get_recommendation_display }}
                    </div>
                  {% endif %}
                  <p>{{ review.content|linebreaksbr }}</p>
                  {% if user.is_authenticated %}
                    {% if review in liked_reviews %}
                      <div class="review-interaction">
                        <div class="like highlighted" onclick="likeReview(this)">
                          <i class="fa fa-thumbs-up"></i>
                          <span>{{ review.likes.all|length }}</span>
                        </div>
                        <div class="dislike" onclick="dislikeReview(this)">
                          <i class="fa fa-thumbs-down"></i>
                          <span>{{ review.dislikes.all|length }}</span>
                        </div>
                      </div>
                    {% elif review in disliked_reviews %}
                      <div class="review-interaction">
                        <div class="like" onclick="likeReview(this)">
                          <i class="fa fa-thumbs-up"></i>
                          <span>{{ review.likes.all|length }}</span>
                        </div>
                        <div class="dislike highlighted" onclick="dislikeReview(this)">
                          <i class="fa fa-thumbs-down"></i>
                          <span>{{ review.dislikes.all|length }}</span>
                        </div>
                      </div>
                    {% else %}
                      <div class="review-interaction">
                        <div class="like" onclick="likeReview(this)">
                          <i class="fa fa-thumbs-up"></i>
                          <span>{{ review.likes.all|length }}</span>
                        </div>
                        <div class="dislike" onclick="dislikeReview(this)">
                          <i class="fa fa-thumbs-down"></i>
                          <span>{{ review.dislikes.all|length }}</span>
                        </div>
                      </div>
                    {% endif %}
                  {% endif %}
                </div>
              {% endfor %}
            {% else %}
              <p>This user has no reviews yet!</p>
            {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

reviews/templates/reviews/register.html
{% extends "reviews/layout.html" %}

{% block title %}
  <title>Register</title>
{% endblock %}

{% block main %}
  <section>
    <div class="section-container">
      <div class="section-wrapper">
        <div class="auth-wrapper">
          <h1>Register</h1>
          <form action="{% url 'register' %}" method="post">
            {% csrf_token %}
            <div class="form-inputs">
              <label for="username">Username</label>
              <input type="text" name="username" id="username" required>
              <label for="email">Email</label>
              <input type="email" name="email" id="email" required>
              <label for="password">Password</label>
              <input type="password" name="password" id="password" required>
              <label for="confirm">Confirm Password</label>
              <input type="password" name="confirm" id="confirm" required>
              <a class="auth-link" href="{% url 'login' %}">Have an account? Log in</a>
              <div class="button-wrapper">
                <input class="button" type="submit" value="Create Account">
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

reviews/templates/reviews/search.html
{% extends "reviews/layout.html" %}
{% load static %}

{% block title %}
  <title>Search Anime</title>
{% endblock %}

{% block script %}
  <script src="{% static 'reviews/search.js' %}" defer></script>
{% endblock %}

{% block main %}
  <section>
    <div class="section-container">
      <div class="section-wrapper">
        <form class="search-form" action="/" method="get">
          <input class="search-input" type="text" name="q" id="search" placeholder="Search anime" value="{{ query }}" required>
          <button class="search-button" type="submit"><i class="fa fa-search"></i></button>
        </form>
      </div>
    </div>
  </section>
  <section>
    <div class="section-container">
      <div class="section-wrapper">
        <div id="anime-search">
          <h1>Search Results for "{{ query }}"</h1>
          <div id="anime-search-cards" class="cards"></div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}